# Generated by Django 4.0.6 on 2022-07-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precioUnidad', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cantidadExistencia', models.IntegerField(default=0)),
                ('IVAproducto', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha de venta')),
                ('tipoPago', models.CharField(choices=[('EF', 'Efectivo'), ('TA', 'Tarjeta')], default='EF', max_length=200)),
                ('subTotal', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('vendedor', models.CharField(max_length=200)),
                ('IVAtotal', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidadesTotales', models.IntegerField(default=1)),
                ('precioUnidades', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('IVAtotal', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.venta')),
            ],
        ),
    ]
