# Generated by Django 4.0.6 on 2022-07-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='unidadesVendidas',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='VentaProducto',
        ),
    ]
