# Generated by Django 4.0.6 on 2022-08-03 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0002_venta_id_producto_venta_unidadesvendidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
